### ISSUE TITLE
getting connection aborted error while trying to connect service bus with java latest version 1.1.0

### ISSUE THREAD

**Issue by pavan538** [Azure/azure-service-bus#116]
```
QueueClient queueClient = new QueueClient(new ConnectionStringBuilder(connectionString, queueName), ReceiveMode.PEEKLOCK);

```
```
19:55:37.551 DEBUG [main] (Timer.java:57) - Starting ScheduledThreadPoolExecutor with coreThreadPoolSize:4
19:55:37.589  INFO [main] (MessagingFactory.java:126) - Creating and starting reactor
19:55:37.625  INFO [main] (MessagingFactory.java:137) - Started reactor
19:55:37.626  INFO [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (MessagingFactory.java:436) - starting reactor instance.
19:55:37.633 DEBUG [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (ReactorHandler.java:22) - reactor.onReactorInit
19:55:37.634  INFO [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (MessagingFactory.java:97) - Creating connection to host 'esb-test-sbn.servicebus.windows.net:5671'
19:55:37.639 DEBUG [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (ConnectionHandler.java:45) - onConnectionInit: hostname:esb-test-sbn.servicebus.windows.net:5671
19:55:37.765 DEBUG [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (ConnectionHandler.java:61) - onConnectionBound: hostname:esb-test-sbn.servicebus.windows.net:5671
19:57:45.498  WARN [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (ConnectionHandler.java:83) - Connection.onTransportError: hostname:esb-test-sbn.servicebus.windows.net:5671, error:connection aborted
19:57:45.499 ERROR [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (MessagingFactory.java:257) - Connection error. 'Error{condition=amqp:connection:framing-error, description='connection aborted', info=null}'
19:57:45.529  INFO [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (MessagingFactory.java:272) - Connection to host closed.
19:57:45.530 DEBUG [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (Timer.java:72) - Shuting down ScheduledThreadPoolExecutor
19:57:45.530 ERROR [main] (ServiceApplication.java:51) - Exception
com.microsoft.azure.servicebus.primitives.ServiceBusException: Error{condition=amqp:connection:framing-error, description='connection aborted', info=null}
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:113)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory.onConnectionError(MessagingFactory.java:262)
	at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onTransportError(ConnectionHandler.java:90)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:450)
	at java.lang.Thread.run(Thread.java:748)
19:57:45.531 DEBUG [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (ConnectionHandler.java:74) - Connection.onConnectionUnbound: hostname:esb-test-sbn.servicebus.windows.net:5671
19:57:45.532  INFO [main] (ServiceApplication.java:54) - I am working
19:57:45.553  INFO [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (MessagingFactory.java:447) - Gracefully releasing reactor thread as messaging factory is closed
19:57:45.553  INFO [ReactorThreade5aff2fa-d6e3-4691-a7d7-46d3e25fb332] (MessagingFactory.java:452) - Stopping reactor
```

**Comment by yvgopal** [comment]
You pasted the traces here. Every exception in the traces maynot be thrown to the client application. Are you getting an exception thrown to your application? What is it?

**Comment by pavan538** [comment]
I am getting the following exception
```
com.microsoft.azure.servicebus.primitives.ServiceBusException: Error{condition=amqp:connection:framing-error, description='connection aborted', info=null}
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:113)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory.onConnectionError(MessagingFactory.java:262)
	at com.microsoft.azure.servicebus.amqp.ConnectionHandler.onTransportError(ConnectionHandler.java:90)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:450)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yvgopal** [comment]
OK. As the exception says there is a connection error. Is your code running behind a proxy or some special network configuration? This is a pretty standard use case and it fails only when there are network issues.

**Comment by pavan538** [comment]
Thanks, its a proxy issue only. when i tried with my home network it works.

**Comment by vinayakmkmishra1792** [comment]
What is proxy here? How should it be implemented?
