### ISSUE TITLE
Receiving messages where the lock has already expired

### ISSUE THREAD

**Issue by marpe** [Azure/azure-service-bus#155]
Even though the lock time is set to 30s in our service bus properties, I've been getting locks which has been expired for 5-10 seconds.

```C#
// .....
_receiver = new MessageReceiver(
                connectionString,
                Defines.JobQueueName,
                ReceiveMode.PeekLock,
                RetryPolicy.Default,
                0
            );
// .....
public async Task<RunningJob> GetJob()
        {
            var message = await _receiver.ReceiveAsync();
            if (message != null)
            {
                if (DateTime.UtcNow > message.SystemProperties.LockedUntilUtc)
                {
                    Console.WriteLine(
                        $"[{Thread.CurrentThread.ManagedThreadId} - {DateTime.UtcNow:HH:mm:ss}] Received a message where the lock already has expired"
                    );
                }

                // .....
            }
            return null;
        }
```

**Comment by SeanFeldman** [comment]
And there's no clock skew?

**Comment by nemakam** [comment]
@marpe 
1. Is it a consistent experience, or happens just couple of times?
2. Also it is clear from your code, but just want to confirm - The prefetch you used for your repro is 0?
3. Is the entity partitioned or non-partitioned?

**Comment by marpe** [comment]
1. It's consistent afaik, the lock of the first message looks good, then the 4-5 following messages have the same expiration time.
2. Yup, prefetch is 0
3. Partitioned

I am calling `GetJob()` in a bit of a weird way though, which I'm thinking might cause issues(?):
`var receivedJob = _receiver.GetJob().Result;`

**Comment by SeanFeldman** [comment]
@marpe could you share the repro?

**Comment by marpe** [comment]
Uploaded my test project here: https://github.com/marpe/servicebustest

**Comment by nemakam** [comment]
@marpe 
Meanwhile, can you verify there's no clock skew.
One simple way to verify is through attempting a `complete` operation on the message whose lock you think is expired. If the complete goes through (or for that matter, you can try to `renew`) successfully, then there must be a clock skew.

**Comment by nemakam** [comment]
Just FYI, for a partitioned entity, it is possible to receive multiple messages with same `lockedUntilUtc` time. This is because of caching that's done to improve the performance and throughput. But the broker ensures that the message is not expired when the message is being delivered to the client.

**Comment by SeanFeldman** [comment]
Ran your repro on west-us2 with a partitioned queue on standard tier and lock duration 60sec - no expired messages.
<summary>Output
<details>
Posting jobs...
[12:01:47, n = 0] Received job, lockedUntilUtc: 20:02:57
[12:01:47, n = 1] Received job, lockedUntilUtc: 20:02:57
[12:01:47, n = 2] Received job, lockedUntilUtc: 20:02:57
[12:01:48, n = 3] Received job, lockedUntilUtc: 20:02:57
[12:01:48, n = 4] Received job, lockedUntilUtc: 20:02:57
[12:01:48, n = 5] Received job, lockedUntilUtc: 20:02:57
[12:01:48, n = 6] Received job, lockedUntilUtc: 20:02:57
[12:01:48, n = 7] Received job, lockedUntilUtc: 20:02:57
[12:01:48, n = 8] Received job, lockedUntilUtc: 20:02:57
[12:01:48, n = 9] Received job, lockedUntilUtc: 20:02:57
[12:01:48, n = 10] Received job, lockedUntilUtc: 20:02:57
[12:01:48, n = 11] Received job, lockedUntilUtc: 20:02:57
[12:01:49, n = 12] Received job, lockedUntilUtc: 20:02:57
[12:01:49, n = 13] Received job, lockedUntilUtc: 20:02:57
[12:01:49, n = 14] Received job, lockedUntilUtc: 20:02:57
[12:01:49, n = 15] Received job, lockedUntilUtc: 20:02:57
[12:01:49, n = 16] Received job, lockedUntilUtc: 20:02:59
[12:01:49, n = 17] Received job, lockedUntilUtc: 20:02:59
[12:01:49, n = 18] Received job, lockedUntilUtc: 20:02:59
[12:01:49, n = 19] Received job, lockedUntilUtc: 20:02:59
[12:01:49, n = 20] Received job, lockedUntilUtc: 20:02:59
[12:01:50, n = 21] Received job, lockedUntilUtc: 20:02:59
[12:01:50, n = 22] Received job, lockedUntilUtc: 20:02:59
[12:01:50, n = 23] Received job, lockedUntilUtc: 20:02:59
[12:01:50, n = 24] Received job, lockedUntilUtc: 20:02:59
[12:01:50, n = 25] Received job, lockedUntilUtc: 20:02:59
[12:01:50, n = 26] Received job, lockedUntilUtc: 20:02:59
[12:01:50, n = 27] Received job, lockedUntilUtc: 20:02:59
[12:01:50, n = 28] Received job, lockedUntilUtc: 20:02:59
[12:01:50, n = 29] Received job, lockedUntilUtc: 20:02:59
[12:01:51, n = 30] Received job, lockedUntilUtc: 20:02:59
[12:01:51, n = 31] Received job, lockedUntilUtc: 20:02:59
[12:01:51, n = 32] Received job, lockedUntilUtc: 20:03:00
[12:01:51, n = 33] Received job, lockedUntilUtc: 20:03:00
[12:01:51, n = 34] Received job, lockedUntilUtc: 20:03:00
[12:01:51, n = 35] Received job, lockedUntilUtc: 20:03:00
[12:01:51, n = 36] Received job, lockedUntilUtc: 20:03:00
[12:01:51, n = 37] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 38] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 39] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 40] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 41] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 42] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 43] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 44] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 45] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 46] Received job, lockedUntilUtc: 20:03:00
[12:01:52, n = 47] Received job, lockedUntilUtc: 20:03:00
[12:01:53, n = 48] Received job, lockedUntilUtc: 20:03:02
[12:01:53, n = 49] Received job, lockedUntilUtc: 20:03:02
[12:01:53, n = 50] Received job, lockedUntilUtc: 20:03:02
[12:01:53, n = 51] Received job, lockedUntilUtc: 20:03:02
[12:01:53, n = 52] Received job, lockedUntilUtc: 20:03:02
[12:01:53, n = 53] Received job, lockedUntilUtc: 20:03:02
[12:01:53, n = 54] Received job, lockedUntilUtc: 20:03:02
[12:01:53, n = 55] Received job, lockedUntilUtc: 20:03:02
[12:01:53, n = 56] Received job, lockedUntilUtc: 20:03:02
[12:01:54, n = 57] Received job, lockedUntilUtc: 20:03:02
[12:01:54, n = 58] Received job, lockedUntilUtc: 20:03:02
[12:01:54, n = 59] Received job, lockedUntilUtc: 20:03:02
[12:01:54, n = 60] Received job, lockedUntilUtc: 20:03:02
[12:01:54, n = 61] Received job, lockedUntilUtc: 20:03:02
[12:01:54, n = 62] Received job, lockedUntilUtc: 20:03:02
[12:01:54, n = 63] Received job, lockedUntilUtc: 20:03:02
[12:01:54, n = 64] Received job, lockedUntilUtc: 20:03:04
[12:01:54, n = 65] Received job, lockedUntilUtc: 20:03:04
[12:01:54, n = 66] Received job, lockedUntilUtc: 20:03:04
[12:01:55, n = 67] Received job, lockedUntilUtc: 20:03:04
[12:01:55, n = 68] Received job, lockedUntilUtc: 20:03:04
[12:01:55, n = 69] Received job, lockedUntilUtc: 20:03:04
[12:01:55, n = 70] Received job, lockedUntilUtc: 20:03:04
[12:01:55, n = 71] Received job, lockedUntilUtc: 20:03:04
[12:01:55, n = 72] Received job, lockedUntilUtc: 20:03:04
[12:01:55, n = 73] Received job, lockedUntilUtc: 20:03:04
[12:01:55, n = 74] Received job, lockedUntilUtc: 20:03:04
[12:01:56, n = 75] Received job, lockedUntilUtc: 20:03:04
[12:01:56, n = 76] Received job, lockedUntilUtc: 20:03:04
[12:01:56, n = 77] Received job, lockedUntilUtc: 20:03:04
[12:01:56, n = 78] Received job, lockedUntilUtc: 20:03:04
[12:01:56, n = 79] Received job, lockedUntilUtc: 20:03:04
[12:01:56, n = 80] Received job, lockedUntilUtc: 20:03:06
[12:01:56, n = 81] Received job, lockedUntilUtc: 20:03:06
[12:01:56, n = 82] Received job, lockedUntilUtc: 20:03:06
[12:01:56, n = 83] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 84] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 85] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 86] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 87] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 88] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 89] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 90] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 91] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 92] Received job, lockedUntilUtc: 20:03:06
[12:01:57, n = 93] Received job, lockedUntilUtc: 20:03:06
[12:01:58, n = 94] Received job, lockedUntilUtc: 20:03:06
[12:01:58, n = 95] Received job, lockedUntilUtc: 20:03:06
[12:01:58, n = 96] Received job, lockedUntilUtc: 20:03:07
[12:01:58, n = 97] Received job, lockedUntilUtc: 20:03:07
[12:01:58, n = 98] Received job, lockedUntilUtc: 20:03:07
[12:01:58, n = 99] Received job, lockedUntilUtc: 20:03:07
</details>
</summary>

**Comment by marpe** [comment]
I tried renewing any expired messages immediately but that gave me an exception. I'm guessing it's not occurring as often the longer the lock time.

```
Posting jobs...
[09:30:04, n = 0] Received job, lockedUntilUtc: 08:30:09
[09:30:04, n = 1] Received job, lockedUntilUtc: 08:30:09
[09:30:04, n = 2] Received job, lockedUntilUtc: 08:30:09
[09:30:04, n = 3] Received job, lockedUntilUtc: 08:30:09
[09:30:05, n = 4] Received job, lockedUntilUtc: 08:30:09
[09:30:05, n = 5] Received job, lockedUntilUtc: 08:30:09
[09:30:05, n = 6] Received job, lockedUntilUtc: 08:30:09
[09:30:05, n = 7] Received job, lockedUntilUtc: 08:30:09
[09:30:05, n = 8] Received job, lockedUntilUtc: 08:30:10
[09:30:06, n = 9] Received job, lockedUntilUtc: 08:30:10
[09:30:06, n = 10] Received job, lockedUntilUtc: 08:30:10
[09:30:06, n = 11] Received job, lockedUntilUtc: 08:30:10
[09:30:06, n = 12] Received job, lockedUntilUtc: 08:30:10
[09:30:06, n = 13] Received job, lockedUntilUtc: 08:30:10
[09:30:07, n = 14] Received job, lockedUntilUtc: 08:30:10
[09:30:07, n = 15] Received job, lockedUntilUtc: 08:30:10
[09:30:07, n = 16] Received job, lockedUntilUtc: 08:30:12
[09:30:07, n = 17] Received job, lockedUntilUtc: 08:30:12
[09:30:07, n = 18] Received job, lockedUntilUtc: 08:30:12
[09:30:08, n = 19] Received job, lockedUntilUtc: 08:30:12
[09:30:08, n = 20] Received job, lockedUntilUtc: 08:30:12
[09:30:08, n = 21] Received job, lockedUntilUtc: 08:30:12
[09:30:08, n = 22] Received job, lockedUntilUtc: 08:30:12
[09:30:08, n = 23] Received job, lockedUntilUtc: 08:30:12
[09:30:08, n = 24] Received job, lockedUntilUtc: 08:30:12
[09:30:09, n = 25] Received job, lockedUntilUtc: 08:30:12
[09:30:09, n = 26] Received job, lockedUntilUtc: 08:30:12
[09:30:09, n = 27] Received job, lockedUntilUtc: 08:30:12
[09:30:09, n = 28] Received job, lockedUntilUtc: 08:30:12
[09:30:09, n = 29] Received job, lockedUntilUtc: 08:30:12
[09:30:10, n = 30] Received job, lockedUntilUtc: 08:30:12
[09:30:10, n = 31] Received job, lockedUntilUtc: 08:30:12
[09:30:10, n = 32] Received job, lockedUntilUtc: 08:30:15
[09:30:10, n = 33] Received job, lockedUntilUtc: 08:30:15
[09:30:10, n = 34] Received job, lockedUntilUtc: 08:30:15
[09:30:11, n = 35] Received job, lockedUntilUtc: 08:30:15
[09:30:11, n = 36] Received job, lockedUntilUtc: 08:30:15
[09:30:11, n = 37] Received job, lockedUntilUtc: 08:30:15
[09:30:11, n = 38] Received job, lockedUntilUtc: 08:30:15
[09:30:11, n = 39] Received job, lockedUntilUtc: 08:30:15
[09:30:11, n = 40] Received job, lockedUntilUtc: 08:30:15
[09:30:12, n = 41] Received job, lockedUntilUtc: 08:30:15
[09:30:12, n = 42] Received job, lockedUntilUtc: 08:30:15
[09:30:12, n = 43] Received job, lockedUntilUtc: 08:30:15
[09:30:12, n = 44] Received job, lockedUntilUtc: 08:30:15
[09:30:13, n = 45] Received job, lockedUntilUtc: 08:30:15
[09:30:13, n = 46] Received job, lockedUntilUtc: 08:30:15
[09:30:13, n = 47] Received job, lockedUntilUtc: 08:30:18
[09:30:13, n = 48] Received job, lockedUntilUtc: 08:30:18
[09:30:13, n = 49] Received job, lockedUntilUtc: 08:30:18
[09:30:14, n = 50] Received job, lockedUntilUtc: 08:30:18
[09:30:14, n = 51] Received job, lockedUntilUtc: 08:30:18
[09:30:14, n = 52] Received job, lockedUntilUtc: 08:30:18
[09:30:14, n = 53] Received job, lockedUntilUtc: 08:30:18
[09:30:14, n = 54] Received job, lockedUntilUtc: 08:30:18
[09:30:15, n = 55] Received job, lockedUntilUtc: 08:30:18
[09:30:15, n = 56] Received job, lockedUntilUtc: 08:30:18
[09:30:15, n = 57] Received job, lockedUntilUtc: 08:30:18
[09:30:15, n = 58] Received job, lockedUntilUtc: 08:30:18
[09:30:15, n = 59] Received job, lockedUntilUtc: 08:30:18
[09:30:16, n = 60] Received job, lockedUntilUtc: 08:30:18
[09:30:16, n = 61] Received job, lockedUntilUtc: 08:30:15
[09:30:16, n = 62] Job has lock which has expired!
Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:970ac817-40a3-4dda-9ec6-35ad614eb7fa, TrackingId:f5479c5d-5d25-4602-ad78-1c58524e70b5_B27, SystemTracker:sarlaccdev:queue:maperss~255, Timestamp:3/12/2018 8:30:16 AM
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<OnRenewLockAsync>d__91.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass72_0.<<RenewLockAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<RenewLockAsync>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<RenewLockAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ServiceBusTest.Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext() in c:\Users\marpe\Documents\Visual Studio 2017\Projects\ServiceBusTest\ServiceBusTest\Program.cs:line 51
[09:30:16, n = 63] Received job, lockedUntilUtc: 08:30:19
[09:30:17, n = 64] Received job, lockedUntilUtc: 08:30:22
[09:30:17, n = 65] Received job, lockedUntilUtc: 08:30:22
[09:30:17, n = 66] Received job, lockedUntilUtc: 08:30:22
[09:30:17, n = 67] Received job, lockedUntilUtc: 08:30:22
[09:30:17, n = 68] Received job, lockedUntilUtc: 08:30:22
[09:30:18, n = 69] Received job, lockedUntilUtc: 08:30:22
[09:30:18, n = 70] Received job, lockedUntilUtc: 08:30:22
[09:30:18, n = 71] Received job, lockedUntilUtc: 08:30:22
[09:30:18, n = 72] Received job, lockedUntilUtc: 08:30:22
```

**Comment by marpe** [comment]
I downloaded the ServiceBus explorer to benchmark the queue and actually noticed that things were moving extremely slowly. Creating a new queue under a different name (same namespace) and benhmarking that was blazing fast in comparison and I haven't been able to reproduce the issue I was seeing earlier using this one.

**Comment by nemakam** [comment]
@marpe 
On standard messaging, performance cannot be predicted due to shared resources model. If you need consistent performance, premium messaging is the only way possible. 
Having said that, We try our best to not have significant differences between different queues.
Whats the namespace name and the queue name where you had slow operations?

**Comment by SeanFeldman** [comment]
FWIW, I've seen some random behavior on specific entities in the past and the only way to "fix" that was by dropping and recreating those.
