### ISSUE TITLE
Timeout exception when I send more than 100 000 messages in short time period

### ISSUE THREAD

**Issue by sshogunn** [Azure/azure-service-bus#202]
# Description

1. I have a task to send a lot of messages between two services in very short time period
2. We use a queue for sending commands from Service A to Service B and a topic for receiving the result of work from Service B to Service A
3. I created pretty simple example(everything in one Spring Boot Application), where I am trying to send huge amount of messages in short time period. You can find **application.properties** where you can change total number of messages to be sent. You can find source code in [my example](https://github.com/sshogunn/azure-service-bus-queue-topic-deadletter-queue)

## Actual Behavior
1.  When I send more than 100 000 messages, I get timeout exception
```
com.microsoft.azure.servicebus.primitives.TimeoutException: Send operation timed out  at  2018-05-24T11:17:36.113812800+06:00[Asia/Almaty].
	at com.microsoft.azure.servicebus.primitives.CoreMessageSender.throwSenderTimeout(CoreMessageSender.java:868) [azure-servicebus-1.2.5.jar:na]
	at com.microsoft.azure.servicebus.primitives.CoreMessageSender.access$500(CoreMessageSender.java:59) [azure-servicebus-1.2.5.jar:na]
	at com.microsoft.azure.servicebus.primitives.CoreMessageSender$3.run(CoreMessageSender.java:247) [azure-servicebus-1.2.5.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:299) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
```

## Expected Behavior
1.  All of the messages are sent and processed

How can I change timeout for sending messages? If it's impossible, could you propose some other options for my scenario? We want to use Service Bus for importing huge amount of data from one service to another.
Thank you

**Comment by Novitoll** [comment]
Probably it's due to it's run on WIndows.

**Comment by nemakam** [comment]
How short is "short time period"?
The namespace gets throttled when you have too high message rate.

**Comment by nemakam** [comment]
That is bound to happen. There's a throughput limit on how much you can extract out of a service bus namespace. 
Take a look at https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements to optimize your performance.
If you need higher throughput than that, you'd have to scale up your namespace to premium tier. https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-premium-messaging

**Comment by sshogunn** [comment]
Ok, I've just tried to do the same with Premium account:
```
2018-05-26 14:43:02.712 ERROR 22112 --- [pool-1-thread-4] c.m.a.s.primitives.CoreMessageSender     : Send timed out

com.microsoft.azure.servicebus.primitives.ServiceBusException: com.microsoft.azure.servicebus.amqp.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:d2c2b461-984d-4432-bcf2-2d91a2c6f4eb, TrackingId:f5638f4e000006090000001f5b091df9_G14_B56, SystemTracker:dela-servicebus-vault-epam-spikes:Queue:vault-data-subject-commands, Timestamp:5/26/2018 8:42:54 AM
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:58) ~[azure-servicebus-1.2.5.jar:na]
	at com.microsoft.azure.servicebus.primitives.CoreMessageSender.onSendComplete(CoreMessageSender.java:509) ~[azure-servicebus-1.2.5.jar:na]
	at com.microsoft.azure.servicebus.amqp.SendLinkHandler.onDelivery(SendLinkHandler.java:67) ~[azure-servicebus-1.2.5.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185) ~[proton-j-0.22.0.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.22.0.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309) ~[proton-j-0.22.0.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276) ~[proton-j-0.22.0.jar:na]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:481) ~[azure-servicebus-1.2.5.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: com.microsoft.azure.servicebus.amqp.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:d2c2b461-984d-4432-bcf2-2d91a2c6f4eb, TrackingId:f5638f4e000006090000001f5b091df9_G14_B56, SystemTracker:dela-servicebus-vault-epam-spikes:Queue:vault-data-subject-commands, Timestamp:5/26/2018 8:42:54 AM
	... 9 common frames omitted

	com.microsoft.azure.servicebus.primitives.ServerBusyException: The request was terminated because the entity is being throttled. Error code : 50002. Please wait 10 seconds and try again. Reference:361ece98-1313-4fa1-86e5-924245f4b942, TrackingId:f5638f4e000006090000001f5b091df9_G14_B56, SystemTracker:dela-servicebus-vault-epam-spikes:Queue:vault-data-subject-commands, Timestamp:5/26/2018 8:42:48 AM
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:34) ~[azure-servicebus-1.2.5.jar:na]
	at com.microsoft.azure.servicebus.primitives.CoreMessageSender.onSendComplete(CoreMessageSender.java:509) ~[azure-servicebus-1.2.5.jar:na]
	at com.microsoft.azure.servicebus.amqp.SendLinkHandler.onDelivery(SendLinkHandler.java:67) ~[azure-servicebus-1.2.5.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185) ~[proton-j-0.22.0.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.22.0.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309) ~[proton-j-0.22.0.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276) ~[proton-j-0.22.0.jar:na]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:481) ~[azure-servicebus-1.2.5.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]

2018-05-26 14:43:02.811 ERROR 22112 --- [pool-1-thread-3] c.m.a.s.primitives.CoreMessageSender     : Send timed out
```
Please keep in mind, that I already use prefetching, async approach, batching and a couple of threads to process messages.

**Do you have any recommendations how we can pause the process and wait till Service Bus is not busy and we continue sending next batch of messages?**

**Comment by sshogunn** [comment]
If you are interested, I implemented retry after 10 seconds, it is only one way to keep it working. 
Thanks for your help

**Comment by nemakam** [comment]
@sshogunn 
The libraries come with different retry policies which already take care of server busy exceptions. `RetryExponential` policy is the most widely used policy.

**Comment by sshogunn** [comment]
@nemakam  does RetryPolicy work with bulk of messages? Or it just splits the bulk and sends all messages one by one?

**Comment by SeanFeldman** [comment]
@sshogunn when you send a batch of messages, they are sent as a single payload. If that's what you ask 🙂

**Comment by nemakam** [comment]
To add to what @SeanFeldman  said, sending a messages in a batch is an atomic operation. Either all succeeds or all fails. Retry policy would retry the whole batch

**Comment by nemakam** [comment]
Receive handlers internally call `ReceiveAsync()`, and if that fails, it will be retried.
But user provided handler will *not* be retried.

**Comment by sshogunn** [comment]
@nemakam  and what will happen if my custom handler failed? Will a message be moved back to the queue/topic?

**Comment by SeanFeldman** [comment]
@sshogunn if you receive in `PeekLock` and haven't exceeded `MaxDeliveryCount`, messages will be re-delivered. Otherwise, dead-lettered. If receive mode is `ReceiveAndDelete`, they will be gone. You should adjust your prefetch count dynamically to reflect error rate.

**Comment by sshogunn** [comment]
@SeanFeldman  thank you for clarification
And I hope the last misunderstanding from my side I'd like to discuss. Sorry for to many questions, but I cannot find answers in Azure SDK API.

I configured RetryPolicy for queue client and when I send messages I loose some of them, seems like they are not resent if I have such exceptions:

```
[06:14 04:21:01.324] [ERROR] [com.microsoft.azure.servicebus.primitives.CoreMessageSender] - Send timed out
com.microsoft.azure.servicebus.primitives.ServerBusyException: The request was terminated because the entity is being throttled. Error code : 50001. Please wait 10 seconds and try again. Reference:c22fb012-bbf0-4abd-98b8-e30081d18386, TrackingId:ed17c401000031960049f8695b21e993_G50_B18, SystemTracker:dela-servicebus-vault-dev:queue:vault-data-subject-import-commands~175, Timestamp:6/14/2018 4:20:35 AM
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:34) ~[azure-servicebus-1.2.5.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.CoreMessageSender.onSendComplete(CoreMessageSender.java:509) ~[azure-servicebus-1.2.5.jar!/:?]
	at com.microsoft.azure.servicebus.amqp.SendLinkHandler.onDelivery(SendLinkHandler.java:67) ~[azure-servicebus-1.2.5.jar!/:?]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185) ~[proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.26.0.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:481) ~[azure-servicebus-1.2.5.jar!/:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

Do you have any suggestions how I handle such errors(I am using Async way) and try resend my messages one more time?

**Comment by nemakam** [comment]
Errors such as timeout and ServerBusyExceptions are retried automatically (unless you have provided a custom retry policy). 
When you `send()` a message and it doesn't throw an exception, that would mean the message has reached the service. It should not get lost. 
If you recieve a message in `PeekLock` mode, then unless `complete()` call succeeds, the message will not be deleted.
If you are not seeing this behavior, then provide a repro and we can take a look.

Also, lot of logs that are logged by the client is done for debugging purposes. They will internally be retried. So rely on the exceptions that the client throws and not just the logs.
