### ISSUE TITLE
[com.microsoft.azure.servicebus.primitives.CoreMessageReceiver] - Opening receive link to 'import-events/subscriptions/events-subscription' failed.

### ISSUE THREAD

**Issue by sshogunn** [Azure/azure-service-bus#217]
Greetings,

I use Azure Service Bus with the following configs:
* Asynchronous interaction 
* Sessions are enabled
* Prefetch count is used
* Several factories are used
* Partitioning disabled (because enabled sessions do not work well with partitioning, see https://github.com/Azure/azure-service-bus/issues/103)
* Java 9
* Azure Service Bus SDK - 1.2.6

## Actual Behavior
I see the following error in my logs:

```
[07:11 04:36:20.218] [ERROR] [com.microsoft.azure.servicebus.primitives.CoreMessageReceiver] - Opening receive link to 'import-events/subscriptions/import-events-subscription' failed.
com.microsoft.azure.servicebus.primitives.ServiceBusException: Error{condition=null, description='null', info=null}
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:113) ~[azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onError(CoreMessageReceiver.java:763) [azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:938) [azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68) [azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42) [azure-servicebus-1.2.6.jar!/:?]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) [proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) [proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) [proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) [proton-j-0.26.0.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:481) [azure-servicebus-1.2.6.jar!/:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[07:11 04:43:50.765] [ERROR] [com.microsoft.azure.servicebus.primitives.CoreMessageReceiver] - 'import-events/subscriptions/import-events-subscription' failed.
com.microsoft.azure.servicebus.primitives.ServiceBusException: Error{condition=null, description='null', info=null}
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:113) ~[azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onError(CoreMessageReceiver.java:763) [azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:938) [azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68) [azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42) [azure-servicebus-1.2.6.jar!/:?]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) [proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) [proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) [proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) [proton-j-0.26.0.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:481) [azure-servicebus-1.2.6.jar!/:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

Could you please help me to understand what is wrong in my setup?

**Comment by sshogunn** [comment]
Moved to https://github.com/Azure/azure-service-bus-java/issues/259
