### ISSUE TITLE
Message cannot be processed due failure ACCEPTSESSION-Error{condition=null, description='null', info=null}, errorContext[NS: 

### ISSUE THREAD

**Issue by sshogunn** [Azure/azure-service-bus#220]
Hello,

I use Azure Service Bus with the following configs:

Asynchronous interaction
Sessions are enabled
Prefetch count is used
Several factories are used
Partitioning disabled (because enabled sessions do not work well with partitioning, see #103)
Java 9
Azure Service Bus SDK - 1.2.6

### Actual Behavior
```
[07:12 06:41:21.963] [ERROR] [net.xxx.importer.importing.boundary.EventsHandler] - Message cannot be processed due failure ACCEPTSESSION-Error{condition=null, description='null', info=null}, errorContext[NS: xxx-servicebus-xx-dev.servicebus.windows.net, PATH: import-events/subscriptions/import-events-subscription, REFERENCE_ID: Receiver_a170a5_08d434aef4ba42bba9a6f270f31c6a40_G30, PREFETCH_Q_LEN: 0]
com.microsoft.azure.servicebus.primitives.ServiceBusException: Error{condition=null, description='null', info=null}, errorContext[NS: xxx-servicebus-xxx-dev.servicebus.windows.net, PATH: import-events/subscriptions/import-events-subscription, REFERENCE_ID: Receiver_a170a5_08d434aef4ba42bba9a6f270f31c6a40_G30, PREFETCH_Q_LEN: 0]
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:113) ~[azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onError(CoreMessageReceiver.java:763) ~[azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:938) ~[azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68) ~[azure-servicebus-1.2.6.jar!/:?]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42) ~[azure-servicebus-1.2.6.jar!/:?]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) ~[proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.26.0.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.26.0.jar!/:?]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:481) ~[azure-servicebus-1.2.6.jar!/:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

I cannot get what is wrong with my configs. Is it something wrong with ASB or my setup?

**Comment by sshogunn** [comment]
Moved to https://github.com/Azure/azure-service-bus-java/issues/258
