### ISSUE TITLE
Getting AmqpException exception while pushing basic service bus queue message to DeadLetterQueue

### ISSUE THREAD

**Issue by manikakde1** [Azure/azure-service-bus#228]
# Getting AmqpException exception while pushing basic service bus queue message to DeadLetterQueue
Below is my code for above implementation

public class Main {
public static void main(String[] args)
    {
        final String CONNECTION_STRING = "Endpoint=sb://xxx.servicebus.windows.net/;"
        		+ "SharedAccessKeyName=xxx;"
        		+ "SharedAccessKey=xxx;"
        		+ "SharedAccessSignatureToken=xxx";
        
        
        final String QUEUE_NAME = "xxx-queue";

        try {
            moveMessageToDlq(CONNECTION_STRING, QUEUE_NAME);
        }catch (Exception ex) {
        	ex.printStackTrace();
            System.out.println("An exception occurred. Details" +ex.getMessage());
        }
    }
 private static void moveMessageToDlq(String connectionString, String queueName)
            throws ServiceBusException, InterruptedException {

        ConnectionStringBuilder connectionStringBuilder = new ConnectionStringBuilder(connectionString, queueName);
        QueueClient queueClient = new QueueClient(connectionStringBuilder, ReceiveMode.PEEKLOCK);

        MessageHandler messageHandler = new MessageHandler(queueClient);

        MessageHandlerOptions messageHandlerOptions = new MessageHandlerOptions(
                1,
                false,
                Duration.ofMinutes(1));
        
        queueClient.registerMessageHandler(messageHandler, messageHandlerOptions);
        
        
        final String QUIT_COMMAND_NAME = "quit";
        Scanner scanner = new Scanner(System.in);

        while (true) {
            System.out.println(String.format("Enter '%s' and press <ENTER> to exit...", QUIT_COMMAND_NAME));
            String input = scanner.nextLine();

            if (input.equalsIgnoreCase(QUIT_COMMAND_NAME)){
                System.out.println("Exiting...");
                break;
            }
        }

        scanner.close();

        queueClient.close();
    }
}

and the MessageHandler class is,

public class MessageHandler implements IMessageHandler {
    private final IQueueClient _client;

    public MessageHandler(IQueueClient client) {
        if (client == null){
            throw new IllegalArgumentException("Queue client cannot be null.");
        }
        _client = client;
    }

    @Override
    public CompletableFuture<Void> onMessageAsync(IMessage message) {
        System.out.println(String.format("Received message id '%s' (DeliveryCount=%d).",
                message.getMessageId(),
                message.getDeliveryCount()));
            System.out.println("Sending message to the dead letter queue...");
            return _client.deadLetterAsync(
                    message.getLockToken(),
                    "InvalidMessage", // DeadLetterReason
                    "Message invalid due to..."); // DeadLetterErrorDescription
//        }
 
    }

    @Override
    public void notifyException(Throwable throwable, ExceptionPhase exceptionPhase) {
        System.out.println("An exception occurred. Details: " + exceptionPhase + "-" + throwable.getMessage());
    }
}

I have only one message in a queue which I want to move to DeadLetterQueue based on certain condition, but when I run the above program, getting below exception,

14:07:56.983 [ForkJoinPool.commonPool-worker-1] ERROR com.microsoft.azure.servicebus.primitives.CommonRequestResponseOperations - Sending CBS Token to 'amqp://xxx.servicebus.windows.net/xxx-queue' failed
14:07:56.993 [ForkJoinPool.commonPool-worker-1] ERROR com.microsoft.azure.servicebus.primitives.CoreMessageReceiver - Sending SAS Token failed. ReceivePath:xxx-queue
com.microsoft.azure.servicebus.primitives.ServiceBusException: com.microsoft.azure.servicebus.amqp.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:58) ~[azure-servicebus-1.2.5.jar:?]
	at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.generateExceptionFromError(RequestResponseUtils.java:97) ~[azure-servicebus-1.2.5.jar:?]
	at com.microsoft.azure.servicebus.primitives.RequestResponseUtils.genereateExceptionFromResponse(RequestResponseUtils.java:92) ~[azure-servicebus-1.2.5.jar:?]
	at com.microsoft.azure.servicebus.primitives.CommonRequestResponseOperations.lambda$sendCBSTokenAsync$1(CommonRequestResponseOperations.java:96) ~[azure-servicebus-1.2.5.jar:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_144]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_144]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) [?:1.8.0_144]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_144]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_144]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_144]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_144]
Caused by: com.microsoft.azure.servicebus.amqp.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101
	... 11 more
## Actual Behavior
1. Getting AmqpException Exception 
2. 

## Expected Behavior
1. Should be able to move the message into DeadLetterQueue 
2.

**Comment by manikakde1** [comment]
when queueClient.registerMessageHandler(messageHandler, messageHandlerOptions) is called then getting the above exception.
