### ISSUE TITLE
Autoforwarding sample is not working

### ISSUE THREAD

**Issue by MaherJendoubi** [Azure/azure-service-bus#281]
# Description

I am using the following AutoForward sample :
https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/AutoForward

## Actual Behavior
Sending messages

Receiving messages

Received message:
        Label:  M2
        Body:   This is the body of message "M2".

        Property:       Priority = 1
        Property:       Importance = High
System.Exception: Expected message not received.
   at AutoForward.Program.<Run>d__0.MoveNext() in C:\Users\Maher\Documents\GitHub\azure-service-bus\samples\DotNet\Microsoft.Azure.ServiceBus\AutoForward\Program.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() 

## Expected Behavior
1. 
2.

**Comment by EldertGrootenboer** [comment]
If this issue still occurs, please let us know and we can re-open the issue.
