### ISSUE TITLE
Message Lock Expired

### ISSUE THREAD

**Issue by Jainit25** [Azure/azure-service-bus#341]
# Description
I am writing a python consumer to consume messages from service bus queue. I am running it in a while loop such that it consumes some messages and then process it and then repeatedly do the same. It works fine locally however, when I try to run it in Azure VM it throws the following error:

## Actual Behavior
```
consumer    | Traceback (most recent call last):
consumer    |   File "consume_messages.py", line 14, in <module>
consumer    |     message.complete()
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 316, in complete
consumer    |     self._is_live('complete')
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 95, in _is_live
consumer    |     raise MessageLockExpired(inner_exception=self.auto_renew_error)
consumer    | azure.servicebus.common.errors.MessageLockExpired: Message lock expired
consumer    | Traceback (most recent call last):
consumer    |   File "consume_messages.py", line 14, in <module>
consumer    |     message.complete()
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 316, in complete
consumer    |     self._is_live('complete')
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 95, in _is_live
consumer    |     raise MessageLockExpired(inner_exception=self.auto_renew_error)
consumer    | azure.servicebus.common.errors.MessageLockExpired: Message lock expired
```

## Expected Behavior
The consumer should start consuming the messages and mark it complete in the VM

**Comment by SeanFeldman** [comment]
@Jainit25, welcome to the repo. Please note this is a broker issue tracker repo, not a Python SDK (readme is [here](https://github.com/Azure/azure-service-bus/blob/master/README.md)).

For Python SDK related questions, use https://github.com/Azure/azure-sdk-for-python

**Comment by Jainit25** [comment]
Thanks Sean for prompt reply. I believe the default lock period is 30 secs and I am not setting it anywhere in the code. But I guess the messages are expiring before that. In another attempt I am trying to read a couple of messages and then mark it complete. I am logging the time stamps to verify if it. The following is the code and logs.

##Code

```
from azure.servicebus import QueueClient
import json
import logging
from datetime import datetime

logger = logging.getLogger('consume_messages')

connection = "<connection_string>"
queue = "<queue_name>"

now = datetime.now()
logger.info("starting application", now.strftime("%Y-%m-%d %H:%M:%S"))

queue_client = QueueClient.from_connection_string(connection, queue)
with queue_client.get_receiver(prefetch=3) as queue_receiver:
    messages = queue_receiver.fetch_next(max_batch_size=3, timeout=300)

    logger.info("connected to service bus", now.strftime("%Y-%m-%d %H:%M:%S"))
    
    for message in messages:
        asset = str(message)
        json_message = json.loads(asset)
        logger.info("the following is the message:", now.strftime("%Y-%m-%d %H:%M:%S"), json_message)
        message.complete()
```

##Logs
```
consumer    | starting application 2020-03-04 21:25:15
consumer    | connected to service bus 2020-03-04 21:25:15
consumer    | the following is the message: 2020-03-04 21:25:15 <MESSAGE>
consumer    | Traceback (most recent call last):
consumer    |   File "consume_messages.py", line 24, in <module>
consumer    |     message.complete()
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 316, in complete
consumer    |     self._is_live('complete')
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 95, in _is_live
consumer    |     raise MessageLockExpired(inner_exception=self.auto_renew_error)
consumer    | azure.servicebus.common.errors.MessageLockExpired: Message lock expired
consumer    | starting application 2020-03-04 21:25:06
consumer    | connected to service bus 2020-03-04 21:25:06
consumer    | the following is the message: 2020-03-04 21:25:06 <MESSAGE>
consumer    | Traceback (most recent call last):
consumer    |   File "consume_messages.py", line 24, in <module>
consumer    |     message.complete()
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 316, in complete
consumer    |     self._is_live('complete')
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 95, in _is_live
consumer    |     raise MessageLockExpired(inner_exception=self.auto_renew_error)
consumer    | azure.servicebus.common.errors.MessageLockExpired: Message lock expired
consumer    | starting application 2020-03-04 21:25:11
consumer    | connected to service bus 2020-03-04 21:25:11<MESSAGE>
consumer    | Traceback (most recent call last):
consumer    |   File "consume_messages.py", line 24, in <module>
consumer    |     message.complete()
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 316, in complete
consumer    |     self._is_live('complete')
consumer    |   File "/consumer/.local/lib/python3.6/site-packages/azure/servicebus/common/message.py", line 95, in _is_live
consumer    |     raise MessageLockExpired(inner_exception=self.auto_renew_error)
consumer    | azure.servicebus.common.errors.MessageLockExpired: Message lock expired
```

**Comment by SeanFeldman** [comment]
I'm not a Python developer so probably not the best person to answer. That's why I've pointed to the Python SDK. I would advise moving the issue over there to have more competent folks look at it.
