### ISSUE TITLE
Constant timeouts since migrating to Azure.Messaging.ServiceBus library

### ISSUE THREAD

**Issue by FBryant87** [Azure/azure-service-bus#570]
Since moving from the old library to the new, we've started seeing timeouts occur frequently in the logs (as in every minute or so):

`2022-12-06T12:45:47Z   [Verbose]   The processor accept session call timed out. It will be tried again. (Namespace 'prod-prem-msg-broker-sbus.servicebus.windows.net', Entity path 'MyEvent/Subscriptions/MyApp'). Error Message: 'Azure.Messaging.ServiceBus.ServiceBusException: The operation did not complete within the allotted timeout of 00:00:59.9700000. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to https://aka.ms/ServiceBusExceptions . TrackingId:3361f483-43a4-41fd-bf92-9b6a8d8595e6_B46, SystemTracker:prod-prem-msg-broker-sbus:Topic:mytopic|myapp, Timestamp:2022-12-06T12:45:46 TrackingId:2d3bade5757842659a196282c715639e_G5, SystemTracker:gateway5, Timestamp:2022-12-06T12:45:46 (ServiceTimeout). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenLinkAsync(CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.OpenLinkAsync(CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.CreateSessionReceiverAsync(String entityPath, ServiceBusConnection connection, ServiceBusSessionReceiverOptions options, String sessionId, CancellationToken cancellationToken, Boolean isProcessor)'
2022-12-06T12:45:47Z   [Verbose]   Creating a ServiceBusSessionReceiver (Namespace: 'prod-msg-broker-sbus.servicebus.windows.net', Entity name: 'MyEvent/Subscriptions/MyApp'`

This is a FunctionApp with a ServiceBusTrigger. Our other FunctionApps are still on the old library (Microsoft.Azure.ServiceBus) and do not have this issue.

We're using:

Azure.Messaging.ServiceBus 7.11.1
Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.8.1

(v4 FunctionApp on .net6)

Whilst the FunctionApp successfully consumes messages, we think these constant timeouts may be slowing things down. Any ideas?

**Comment by SeanFeldman** [comment]
Sounds like SDK issue. The underlying **service** hasn't changed.

**Comment by FBryant87** [comment]
Even though we use the new Azure.Messaging.ServiceBus for bus interaction, we still use the old library (Microsoft.Azure.WebJobs.Extensions.ServiceBus) for triggering messages off the subscription in the function app handler - just checking this is the intended usage?

**Comment by SeanFeldman** [comment]
@FBryant87 you're still referring to client SDKs, not the broker. `Microsoft.Azure.WebJobs.Extensions.ServiceBus` is Azure Functions In-Process SDK. If you have an issue with that, I'd be raising the question in the appropriate repository as it doesn't seem to be a service side issue.
